# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:bgE4sGz6nABK,iv:gqVqjuQTgnLHMjGVv/h5pgPkyi0PYE+/Z+9fJ2t3QZA=,tag:HaB9hJa/TCCa1pnlJW45dA==,type:str]
    admin-password: ENC[AES256_GCM,data:bnmenR9WQ4P/O8t/gOIjFCZgfElJecE=,iv:1zdEmRdi08vGOEnioYa/n0g3TDh59OwHtNdIWjfplzY=,tag:6XM/KUhVuamWxO5p+uvX2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVERyclJVanQ3YmV3eGpH
            bjZiSFNRUm9PbFN5dGJyelpEc3FGcTBzbW1rCmxTbUp1VGQ0MkhvL29mR1piWTM2
            dmhqQ2RQTlR0VHZjaGlJVjlZNnJmUFEKLS0tIE04WWNSam1zYWxyaURwN3p3STF0
            T3FUY2VhQURFMVdYQXRiaWRwUkJpaVUK8vvHcR9E2CI1o6pZQTa7/RTcqY9STeA5
            6Wzbc74JyOPWlY3xwYz+SaQUYlhLzHTwkdpnPW4211Zk5n/Fk2Rn1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-27T12:22:07Z"
    mac: ENC[AES256_GCM,data:HTlykcNLst9YqPSV43eqwRQo5dUcsTNVD9oIYMAEBrbRRRbizYJCfBH4qCRMx2Z/UpOiDtfQH/sI72wtc7mPwWnupTGFnAQ5m8kXth2rZ/9E5CCDNoXTgWEH87RrwVkP0BFydio+SuoMYTfj0xwrkNba7kFYreNc4Me5dGQV4m8=,iv:FuwNcUGcZaJWWiJYaWzOr3tCu6ATk6P1l/MJnUg2z0g=,tag:3LGeawLmCiXEA54vSoJ/fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
