# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:bgE4sGz6nABK,iv:gqVqjuQTgnLHMjGVv/h5pgPkyi0PYE+/Z+9fJ2t3QZA=,tag:HaB9hJa/TCCa1pnlJW45dA==,type:str]
    admin-password: ENC[AES256_GCM,data:bnmenR9WQ4P/O8t/gOIjFCZgfElJecE=,iv:1zdEmRdi08vGOEnioYa/n0g3TDh59OwHtNdIWjfplzY=,tag:6XM/KUhVuamWxO5p+uvX2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVERyclJVanQ3YmV3eGpH
            bjZiSFNRUm9PbFN5dGJyelpEc3FGcTBzbW1rCmxTbUp1VGQ0MkhvL29mR1piWTM2
            dmhqQ2RQTlR0VHZjaGlJVjlZNnJmUFEKLS0tIE04WWNSam1zYWxyaURwN3p3STF0
            T3FUY2VhQURFMVdYQXRiaWRwUkJpaVUK8vvHcR9E2CI1o6pZQTa7/RTcqY9STeA5
            6Wzbc74JyOPWlY3xwYz+SaQUYlhLzHTwkdpnPW4211Zk5n/Fk2Rn1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-27T13:47:42Z"
    mac: ENC[AES256_GCM,data:I1JTn1kbIgakYicXJHF0lheED8KQvPT1nPZ5Q8qgpkJIJcL/1FB23E+kyxLuJnHQxnlblq49d3bem9jQgyBv3jqCRzsSbhbQ9DVK7HFSqnG0czvqWfT6qL5Zg9wmkiR0Ao2DPLwOSgnKjPo8Z27p1/h81etTUxxnAzh+De2dqEE=,iv:CEKcvaddemnmNEO2xVN8g69+5N3MJF9qv/LX/0eC7do=,tag:9LALA+hUif0+vxD8QK4Y+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:66pgl/ou8Ck=,iv:mj/5kEZX3Y1NK3aYnGS4lMY4fYq+rnG/cbxLagdl7qw=,tag:ClE5sYAu1vota0QsPcAKNg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:fCPaSgeyk3jcE3fAuweK88vSesOPwQQK,iv:nPpj6+DJQoL94ZHY+7cvNNRtjs5SKW8x+j3P/fAY4CQ=,tag:CfXzM07OT/hEq8WCyP8fCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVERyclJVanQ3YmV3eGpH
            bjZiSFNRUm9PbFN5dGJyelpEc3FGcTBzbW1rCmxTbUp1VGQ0MkhvL29mR1piWTM2
            dmhqQ2RQTlR0VHZjaGlJVjlZNnJmUFEKLS0tIE04WWNSam1zYWxyaURwN3p3STF0
            T3FUY2VhQURFMVdYQXRiaWRwUkJpaVUK8vvHcR9E2CI1o6pZQTa7/RTcqY9STeA5
            6Wzbc74JyOPWlY3xwYz+SaQUYlhLzHTwkdpnPW4211Zk5n/Fk2Rn1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-27T13:47:42Z"
    mac: ENC[AES256_GCM,data:I1JTn1kbIgakYicXJHF0lheED8KQvPT1nPZ5Q8qgpkJIJcL/1FB23E+kyxLuJnHQxnlblq49d3bem9jQgyBv3jqCRzsSbhbQ9DVK7HFSqnG0czvqWfT6qL5Zg9wmkiR0Ao2DPLwOSgnKjPo8Z27p1/h81etTUxxnAzh+De2dqEE=,iv:CEKcvaddemnmNEO2xVN8g69+5N3MJF9qv/LX/0eC7do=,tag:9LALA+hUif0+vxD8QK4Y+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
