kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:BXG4huimzcGmzA==,iv:5ehUL1n9zVjR6tvxI0f+X1Uh9fvptSrRIOmcs/GMxTI=,tag:OJBubnCxG9IOAYaKT9PT7A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Y3+qoW4s02qDEyysstNQaXJaFZR51qzo9w==,iv:OD7B7jNGUx4MCrzpkgQuVS4iHRhpYrfE4x0ljALgUek=,tag:H/wLgl4C7dHVxDiCCXoP8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMVorbDRkd29nRzAwMXNn
            d3NXaHpiL1p1YmNEY3M4R1dnWDlHR09ONlZvCk8yZXM2anZFZkFJNlA5MVF3N0xs
            RWR0SGIrS1hOdTQxaXVBN3VOZC9DUjgKLS0tIGtBZ0ZoazJHUjczWW4zbzljdStE
            R0dtbmtwVU5ldTd1U1RyaXMxclFpU28KQYHFGtkhaEaM4GlpAueYmKQK0w7yWU8+
            gAVrFkMO6XQOcMucUr+k74MyqAo5VH9j5f8xsciDAIhJ6su9yUvv/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-22T11:34:39Z"
    mac: ENC[AES256_GCM,data:T417WpSFyRSR/VlkhgehL8myTVNwCE2et8oOrykAMlmA4lsN3wttf410oJ+5NLkTCXxuDjYDKspUc0ICb9gpRPwq+nOrfuxWeb5tkbm+JIvXAFDLGVHXV1A1nn9Fp7e/i/OWShCrpZWXWi8wCiG4jHwG7/rc+Y8a+3ruV64qrJ8=,iv:8xHgSEJ92GGLnG9I5locCxqFboXFJqNZDWyjCir68gY=,tag:ELWZAUZYqfTt8IkWpaRxFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
