kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:WF7NPthZEpl4Y5SC4gk=,iv:cUCK/lUvR7i4OtCdIOc1zSFM/g0Te2iJrWarbCJk91I=,tag:ko3roYb1kuP7reu9exAyhw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:CwU7mOGMzrbl/AP3ATAoLF8ptUZkCnijZA==,iv:gvJLpjqmn4kxq3u/V0LFuVlippAX023/jjSDXImEyXI=,tag:WgbZxg2HDmg+pwYpcoWWrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMVorbDRkd29nRzAwMXNn
            d3NXaHpiL1p1YmNEY3M4R1dnWDlHR09ONlZvCk8yZXM2anZFZkFJNlA5MVF3N0xs
            RWR0SGIrS1hOdTQxaXVBN3VOZC9DUjgKLS0tIGtBZ0ZoazJHUjczWW4zbzljdStE
            R0dtbmtwVU5ldTd1U1RyaXMxclFpU28KQYHFGtkhaEaM4GlpAueYmKQK0w7yWU8+
            gAVrFkMO6XQOcMucUr+k74MyqAo5VH9j5f8xsciDAIhJ6su9yUvv/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T12:26:37Z"
    mac: ENC[AES256_GCM,data:IAcN/dwYLt78H1eQkxiAZb6O/+O3BtuANln3bTxlA6R4gV7IvBy9bxa0mIG6ZT+Y1zHyHxcnJwkyMaTh1YXgS7gXc0w06d9PvdwT+QjFKB/Jr1pXmWqv+4XfNe/m4ITZwdruqyPzoPFxLrxAOPwHyqJxkoozgNI9BOD4ZZfs0vc=,iv:L0UvCKRW+7XIf+mhMZl7k73f36S+dND/f8kmxzrjVo8=,tag:POeQBnHoeVB2ETAD7VFmhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
