kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:BXG4huimzcGmzA==,iv:5ehUL1n9zVjR6tvxI0f+X1Uh9fvptSrRIOmcs/GMxTI=,tag:OJBubnCxG9IOAYaKT9PT7A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:n9Hrqid4oFT2ONA35HREwdMf529TNxV8h3s=,iv:yWCBqxR+2Zszao/uRsMhoPPybvZm7us4Xn8mDveQuzM=,tag:+IVg0nA1aETsy7Exa14RNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMVorbDRkd29nRzAwMXNn
            d3NXaHpiL1p1YmNEY3M4R1dnWDlHR09ONlZvCk8yZXM2anZFZkFJNlA5MVF3N0xs
            RWR0SGIrS1hOdTQxaXVBN3VOZC9DUjgKLS0tIGtBZ0ZoazJHUjczWW4zbzljdStE
            R0dtbmtwVU5ldTd1U1RyaXMxclFpU28KQYHFGtkhaEaM4GlpAueYmKQK0w7yWU8+
            gAVrFkMO6XQOcMucUr+k74MyqAo5VH9j5f8xsciDAIhJ6su9yUvv/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-22T00:27:20Z"
    mac: ENC[AES256_GCM,data:to2joQuvhhdjrFKem3M7PYHQS9FZ1nK6UojQaak165goqsxywdEPmcp4wdStFh8PWsnwPoGRwLqtCJ7Ja7HeZHTphAGH8zQTKFV3cBfDAblua/h0CMFXE+gDHB7SVlzZmnuYPIiVF6ydbj22P7Llmq4dZh64SrCaWsoBGr8891U=,iv:DqVwBJhn30HKEZCzwlZz1sDudnQpxBIDYdD3bW7GW0s=,tag:SR008tvcRD3nryRci4xR2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
