---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant-code
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 4
  dependsOn:
    - name: home-assistant
      namespace: default
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/coder/code-server
      tag: 4.10.0
    env:
      TZ: "${TIMEZONE}"
    args:
      - --auth
      - "none"
      - --user-data-dir
      - "/config/.vscode"
      - --extensions-dir
      - "/config/.vscode"
      - --port
      - "80"
      - "/config"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.home.arpa/enabled: "true"
        hosts:
          - host: &host "hass-code.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: config-home-assistant-0
      backups-ha:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nfs1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/k3sCluster/Apps/External/Backups/home_assistant
        mountPath: /config/backups-ha
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: ["home-assistant"]
                - key: app.kubernetes.io/instance
                  operator: In
                  values: ["home-assistant"]
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
