---
ansible_become: true
os_timezone: Australia/Sydney
os_packages:
  install:
    - apt-transport-https
    - arptables
    - ebtables
    - nfs-common
    - linux-modules-extra-{{ansible_kernel}}
  remove:
    - apparmor
    - cloud-init
    - plymouth
    - snapd
    - ufw
