---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - cloudnative-pg-charts.yaml
  - dysnix-charts.yaml
  - emqx-charts.yaml
  - external-dns-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - kubereboot-charts.yaml
  - k8s-gateway-charts.yaml
  - metrics-server-charts.yaml
  - rook-ceph-charts.yaml
  - runix-charts.yaml
  - stakater-charts.yaml
