# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: downloads
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:sf6/avFuFYKyFHFZ2nYAcJjFbDcDlbExk86PzFkELMqrraxQeRPEPhZYCKs=,iv:PYQWenvACsSDAJysEGqDMm/EgFtWxFHq7QKHQy7ojwk=,tag:GITO6TNHhzBA/UrLNN4mtA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:cq9qiN1rUuQ5rg5czgskZvFguM6SboKk+2EIgYo6FYSQ797M0YOIa3HT87I=,iv:qxqbD9TN7UOtfC/RCgmZn+zVbqxerG1lnmJY/Yd9DWE=,tag:Vv6WXMf6m9PJL2Zn4Xxvmw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:CmchjdiA13slRw==,iv:B6udlcY9ptRmxBHIQVjl/FhhpnoA7NxSHxpO0qB4OUk=,tag:b/AEOzpJQP69DqER6xMZPQ==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:G2xk6OTGXJCV0G1GguMi,iv:fk+IXN61G+gek29LI6EwB4QlL6fbX5/IodF3KX6dHXQ=,tag:tC69Nqy31a5Oibsc4rBRhA==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:TqfDvCbl7gI=,iv:GQuUMDfsm7EScUWps74BTlnHTR9HAelfLLJaziTvAuc=,tag:XIHWpTbEsTBZPIS0JoOOOg==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:npkzaUng4pehjg==,iv:0cJeV4zjeiyub3F1ynoZ/H+fn4WkcxfK1wxWTYOdNhI=,tag:AK33TiePthOUmzoPml4PHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NEcxOXVQTnpSUnpKQ2R0
            c1lFekRZUmVoWHFWaW5zazRqV0NqWGVRbVgwCk8rc2dTWS9GUUdtYm1nNHdXMzV4
            QmxsaVJrLzFLUkY1WHprem5WaWIrdlkKLS0tIE51dWRGWGMveFhNTS9LRGQ5MUcr
            NWpxQ1Q5UDJBTXg4WmtFRXpnYnFhMzAKBb5Cn18GxtDPASP510vsJF4aa0BQO8vq
            4y3gzxfFGHJt3Bo3+Uq9OROmFqS8OsmFkzwB+6Q6/Qi7tsXFVPeGqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-18T13:15:13Z"
    mac: ENC[AES256_GCM,data:iyZ+/tshKd6jxnR7Do/Ed06hmE7hKMaCel9ffA+IMJuuHpLFHHlVIE/PBh6ZJOyUK8WTUtbmQBHrHyuxJ7o1EF1/MvKwnDZjzw9cGSzJTJZboeKelreGBBuFEJFinzkFPHYopLRUTClIkGVLrGjM1sf6H2xM4ZpNUu0DHYY3Lxg=,iv:af29JcS2Sru1XomQcSDDXaNb1TY6SF+mTOTomMIl0Mc=,tag:NGY5hbs/0/3DmzuIMOUNKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
