{
	"data": "ENC[AES256_GCM,data:4a/Te9RSRJFjH0SPPKfTrre4zPwgBxagBrm+7IPQNOS5QD8QHlBjQKghyj5hlWBc+RQwDc/UxgYiK07hpU2TjZWS6yyGAwToCGPrlLXFcevw/FRmBcPv6ejs6BN1KxNqPxPr+w+zJ6z7IAzu+D+6Ycbs+uzLx0eKhvUwV3geYtUCIguJ/TEsafE0sm5DRMEMB2uypJZ3bYz7CNBBEy27FrTva9oB+pXqkJPDuntfEj3KNDcz4BNtuaDQ152T6BFRHETYr6mE5747TOsvZa1tKVjmQ6WOdHRyee2x/5mg5LTLvAk7mQ/Xa0DwYidOLaXsQESt01Dx+I1isXwofGW+MDEx8Zp8ZRTT8uoKqm/n36yFuf7qPkuSsMsg4lAncxzRbgzW95XgxbF+KtFhkQXOMmblo0R2ELsJrMa0JRdnz22Yo94n8EdbLSU3VVefAu535T1y5XlXyidsSpLUAYKzQ/8sN1NJUyYAlXkTim3zL28CISrD7QHrs37aXlIOTHC/fC3mPHKovmpjoEkIDdJx8idvF5j1coQUCwmAVck+5hqg9sWc/oFHeU78E2Pm2yUaQzduo5eH8o89pySBTWf16OxFEKMEVhoIaZGMRwauH27G00mPWhJQYt2SpX5Ho92qHuRKDee/AmWwjatIOy7hxn1vafFb7c5MgpXshnW6dRLQ8QatM4C0+boD17GDjwf6c31WazQ2AiMlFJVaY27oeijOdynTEfijn/gqddLBPBFg9EQPPA2e5eSV6Fbk155ZnJfizBXeJM1SgkCqPSWljHK0wS2obSGWhRduSBayrmP9v2FNcKopjsTV/4ewi7P7XK2rWAc5uYLQOrQbDNsoe4qTTPKGGhaGIUs+txNSV2hWgPHafcmR62mzMUUJcp+A8uqP0KVUFUzTPCs3HRRJaF9pMENI1v8IbasxH3fqwvoOiI77T4OrwHLMqvk6CoZEqfGC++6MXULO7peB5cqpgFi91EtAm9xDDzPQlj5fu4/qjt1FvdzdANQLI+uXD2P7xwdpIZ0ipIP+Mv3+q8hPkg==,iv:3ZI1Sb6eLAAT8VgEjB/RLrVr/GS53sesOh+qrnMZRAQ=,tag:BQVT6C0oebpReDxmC1RjOg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b1VFYUs2ODBObnU3dHpj\ncU1CZ2E2N0d0ZThyTmJwalIxaUtWM0t5RERZCmV0Vjlsd2hPb0xxOTVFK2RuaHNY\nV0NVRzdmTDFoTFdIZG5kcXo2VllJTFkKLS0tIG55ays0eDBMeVNDT25PMi9ZZ0FK\nbTlmbXpOZGRIb2pwYzhRd25Qd2hCN0kKlC+3MlTWTHe7sZP7JhtkqMt9K2U5ImsR\ntbdEFBN+tV5SHU9Soa6NUpbUHFfoTHFO9xieQy01iX24pcHJrYWTzg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-11-29T10:31:50Z",
		"mac": "ENC[AES256_GCM,data:LfZ+4x0GJa2JfETmLWwM2rW2j0147zMYV1LFKxQAfQR5fVC/0gTeWQ5G9UfhCbB0xUZaBJxNhzFwI9DIew30RvbO1KYns0x5KuEPKrni6PtwNyT4xedAu+eKIQeX6LW2+kZSU9bRDgtJfZg0oB8R2orMIq1Do1pmJJnedMN8ccM=,iv:SXp1lIfuDCq5vjMviICnmNlWvmLRdPg5gx3xsNc3TC4=,tag:oYO37w43vbjOeEb5p2cJeg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}