# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nest-rtsp
    namespace: default
stringData:
    GA_OAUTH_CID: ENC[AES256_GCM,data:rVaXcY2MbyBP+t60rBFoVdKh3Vk/cIIZlwqgNvtGTbVKTQ7np0ukLk2XQbTV13CJtnQUPKGLcEFEErWjv4Dwufc2cmggw4p6,iv:HJllYVnqMEUCBHdKlPXYI3ThdJq8rITb2FFrvTE//pE=,tag:8Nn7P4lEztrRwROZ8f9XZg==,type:str]
    GA_OAUTH_CS: ENC[AES256_GCM,data:RqQqVhTj/nZ+bdHBmq0RqyXFMbnRaE2O1SNgPEAv7nrGF/Y=,iv:9qXBN1eYv4uoihg9UEET641osqsQBcheCQdSU6+Kras=,tag:fzEF8HHuvzGGW1Pw2HH5JQ==,type:str]
    GA_SDM_PID: ENC[AES256_GCM,data:uc466UKcIdbhlic9MtTIIqBV9uY1YK2REejkHy9C5iLa31+Q,iv:JOheRX0qACXxWGhrJG6jq5S1ju09gRvqNl9OzeQ4DGI=,tag:eBy1tRWPq18IwBpC/ikZFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN1RkWEtRZXNBQmpmOWUz
            T2E2NzBCSXpHeFVtbnZ1cnBRTmdhUkxYb3hBCm1oMGRLQnhWUjhDRmYwK2h3bW5z
            amVnZWxpZ2ZhbkEwRG1nOU4xUG1kbTAKLS0tIDZUZ1hBajV6ekU1RkIxbGRnbU41
            UHhBeFRwT1FhMEVVUktlbjQ5KzYrMVUKOZs+Fl648t0xTgX3+hcURr+g9n+KQzj5
            Snm+0QS80BiimPlmD/Zeybasc6LMlg28o2Sdh1xD9iGgoXBZHVw5KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-31T13:52:55Z"
    mac: ENC[AES256_GCM,data:SFz+c5Ul3LIoIot1RG32K5O8kqq06XF1XxVhTDGzOWY5UL64xANzdi5Q2eLUw1tAahnciaJ22dIQx/cIPmGi1AUG5p3loLuuyQFruu67I3222RTHWWcECuuZywFvrXTpAmtwemGNE0MJTw8dd533SfNLe+ryR7owjp3idbxjcjs=,iv:4zmHZfP8aRslK0ENqA3E2deNp+nW3vwWSJz+MdtKqEg=,tag:8JGJiVGn2fq0WqdEr/a1vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
