kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: smtp-relay
    namespace: default
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:2/Jd4Of0OvCoGvjrjqrmtw==,iv:UUMrbZ0Go6kcgoYKEINFtKmfxXHFI+NVBgFsvE24gi0=,tag:GV/dCZhVfjFfOEDjlTu2Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnamYvQjF4TlNRSExYRzFo
            Qml6cUVYdmhSZU94RVBCMk5iM1BDYmVQanc4CllSdlVVNXlYYlpZbzV0bGYwc0ta
            eU1GaEFQZ2RoZkRNMGhyZ2xFOWg2a3cKLS0tIDNyWmQ3a0d6RHVKQW1FM2RvSW9v
            NWd5dGNaTUg1SXptalg1NXFVYXZQWUUKUJ2H0MKsYvGT8/Bnsn06E2EXaHgPvdsS
            OmPXB87EQUlZjzvH3PexKKGBFHCsBIaYIWq4aBhCGfE74SP/kNvIqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-28T11:44:32Z"
    mac: ENC[AES256_GCM,data:v1b+3UmyhWaWrKz1Iz/Ho+ma4bD6XXDKv5o3FTRn9NP1IUQlfvwwOozfoxaTCqpGVt03LM3p2+UFRyqMRjyZ5QpybSHpU7GVuJBsykB7jY/KDxzeWLshYUxZqQXG4hBuG2I0wAGk2xu7I3xvU8F8j5rVLYJnBat4aH5AIlDHQow=,iv:HdVNxi+PrIkMzF/jZx8Wpz02IkQiJyQDLHKr1YBSpbg=,tag:LtQuMrUhj2J3yNNccz5rDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
