---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app esphome
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/esphome/esphome
      tag: 2023.4.2
    env:
      ESPHOME_DASHBOARD_USE_PING: true
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: true
        annotations:
          # external-dns.home.arpa/enabled: "true"
          # cert-manager.home.arpa/enabled: "true"
          # auth.home.arpa/enabled: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host esphome.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: esphome-tls
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 1
        memory: 1Gi
