# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Q/YMCwA4YDrpNbh8hwyUujvZ,iv:PpRlH5zwkZ5WAQQR9MYVPiE59ynVg8OemZV875HGCoM=,tag:ms08pv6nbfyFcPHKoOAE6A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Km97mbtSjykhM8SI8ogdWqM5/juEaVk2TR3ykvcl6IuIcHdqig==,iv:z8pb6Gg3AmjPJuxRijF0sdO52adymNiIIYiMbm7TshE=,tag:gUHJOFA2BvGHSb/seq7AMg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:K2yD4uAXfJoKf22UUaCCkjBoaw==,iv:G+4E0Bz315/Zhvrl2Wp6BtbJMk24Kqv7xezxL6qqYcY=,tag:477iOrkfpGaVSmHKGH+2Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtalk2ZzhFRndVbGcrbnRk
            UEY5REN1WmdUOGQxT3F6Y0xWYWF5WmpQb2dNCnBVS3JaeTdLV21USVhZRlF1OEFk
            RXF3VlZ3QWlGb2lyQXA2Um9kSzJvd1EKLS0tIDJyMnM5ZVNqaEJTYVdLRThna1NL
            bFR1SEVjS01XN01VdzhtMzJ0a2sxTzQK2ayRW6igKOY+wq5isfEf6ZnpVuUMyqGh
            Vbet/JjRmS68MJpl/zGyYMjs5cBW12pZ013AyTeqOHMwxycp6QA7lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-11T06:04:15Z"
    mac: ENC[AES256_GCM,data:yKSNixr30odekLVTlMhcfbJBHSn65/DPlVdGF5fbMPiu9ng9JEjTCIk5NLHPVgiuReXiNkvNxz3QiDj76vuWsN94/LSPjo7HKyZRIUOrTxKtJi1F6/GXs9hcRDll90iwQQrfUkV8JJhq7KnrM5DDyDzzhPhhFrt8YeQEPoAAqTQ=,iv:l6BA8zBB16anyNhrXpMMAd8Xj6bIE51T6oGgzHndQP0=,tag:Ifpiemxi775Yo4oo7Ecqrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
