ansible_become_pass: ENC[AES256_GCM,data:8BIR4FsTxRbEELBQeA==,iv:qaAnFD2Cr2r1tyiW54utGzy84oilg0qbHxVLnCK0FCk=,tag:d4NVRPGK4oRgMp3hLtyGPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcFduNEIzaVI3UXdFN1pu
            NitPbklUcjNQVmNHQ1lwUldSTS9KNG42d3d3CjRsdC8wRW5lQ2o1a29SVWhKS3ZP
            Z2dlclRDSXhPT3BhMkM3bXFVSnIzQU0KLS0tIGJ0MExFd1M3YUJsZ2laWk9oQXhi
            cnZ6UkdSZzNsdGlqS1dFdUJmY0dNbkEK6cf1h6yn6fr5/+UIrpo1FWfdu6xDuaBH
            /KYO/2S3pyIE7aol10fU0d2iXKscIcGRQrBGa8uib//rUmGdEFYy7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:01:10Z"
    mac: ENC[AES256_GCM,data:vLkZwr4Jlw8xQJzZTbFebRB1AJuDJErdjgbPBj98Gxy749Xp+n6StyZ9QkmLFPMnjGcY+0/+pImlhHzrioMhPiRAyqhboUwn4QMA3KRhGqXKJO2pzosH23fN3pAU3tUwpCgx31DtQIhRHWuFjf2C9TsM2bepGd9PkjVlJtRsrE0=,iv:hvVbfDc9qzXA0sW/aj5iZ4frhu6XN3OmKRQWKB3l0AM=,tag:Sf2OvJnT8HS6exRYTLnKKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
