ansible_become_pass: ENC[AES256_GCM,data:AtOq4nItnUnIsk8GAA==,iv:h8CkuQKuYtXkHXGTGCT/WogarGNMEcBSAKVnlcB40xE=,tag:yG04lfuQpTg/AywZ6aQJ3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM3Mvc3loUFR1eGRSYi9Y
            c2hqS2hFcDF5eVB3Q3h4TlNmNjNlMHhwYUJvClEray9qQzk3Wjk3eGhEYy9qZWhj
            a0x6aDlqc0RPRDNMR1QzWVljbUx6QTAKLS0tIDBrZlAwaHdodEZTcURuVlJudHY2
            NWMrdUg5WWhScEpiTWVoYVpsSGFWMEEK9TH5v7/+JGKwcZHfvAYB93Z1kwnem2Dk
            MBtCuHSKtIQG8Q4RM6mWcTJN7l6m5k/dX2Sr+86xU1OpC+r4J93JgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T08:00:06Z"
    mac: ENC[AES256_GCM,data:qKR86iwdjgovY3ignCeWoAbPoxVRIqBkkfyUVFlNcVs1LbY8JRhRReABo8c+NUl+icUsS/bOp+MN7n/Be6C1XlFiMlCz1MAsnNSMbkUZxgY2a+ik+uSBAzLGAo4HDDlYJPn8sGOVf0kG2VwJp3CtsMjpPP+ZlrD8gOurQNNQ2rU=,iv:SEQ7NX2mAbviO3NGLpBmST2VrjvMsIoPlYzOf6BS8hA=,tag:MMfohi/ke88lIqbR1MFUtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
