ansible_become_pass: ENC[AES256_GCM,data:LyNL1sA2F0mMy0RBNw==,iv:SnkyzLwri6ewTTezLQV+QAP/4aXrKAx7WoEE/Yc3J5w=,tag:6GjpyAI8AZ68gTHSJ59JvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaFNublVIZDZMcktmV25q
            cFJWb1g4ZExIZFZIcHdMY2JwMTUyak1SclZvCmhRb0RBY1V2TFpObW9LWkFqcTRH
            N0w4Z005ODFnYmFOYmZ1ei9JK2xqd0kKLS0tIExGaThNNGNXWXFvU1JySEJBbGtI
            VkFiR2E3NFY4UThCRENBT3lTaEJ5RFEK6Ch1rAsXKNe1mR0RfdXSWGUGWLcB48tZ
            FE8MIHyuDMcicr+ObMdWjVngucWSpnQKynKlWT29R4RXqjL8tYE5mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:51:24Z"
    mac: ENC[AES256_GCM,data:3sQSi5M93eUqTWjSSz2xyOp4J0Qpv260K2LkBO1xkIsmnbg44aP+wmLgepNFlvkQt3TdUUgATu5y/r+yeBbopZBbuZevYbIgVHL7hMeZuBBZNJYp9UQozDMLnqFDzdpbZVieZcCaEKGu7Eds+2k8kwOLujdAlX79AqW85QYoZfM=,iv:L/A2FgBG/01/a9YoW72Po6joli1mUhXmxDGI6MpyOWw=,tag:f0sn50NBvB+8puzh1tQKZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
