ansible_become_pass: ENC[AES256_GCM,data:n0UZmIW4+KjW59bD7Q==,iv:dJi3iNyDRmYAlw2a4I3vHjB68TndnFRE7SXyZW8HRE8=,tag:cOTbRkxOGXuxLJoa92CfJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWk41MjA5SXNtWEowa2NE
            NFYwMFliTWw2MnE5YjlaVXo4UmZvcXpwUkV3Cjl6TmFzSjhVK2ZmbzlDdXRnYWc2
            cTNkT2hkam1GTGhmVG9WZTFzYWFqRmMKLS0tIEJzeHBNeUhvbzFhTCtwRFNUNjN1
            Mmp0U2VMRVUwQlMwSjFkQmJ1cUR5a1UKo/JvlSJVzHOpmo/NyJWkSfap/rMJbmst
            I8fokDR5qGXft8DsOgjc7f4W/m1YriVQUGhp4ZHJs3uPjwZWm1/ECg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:32:23Z"
    mac: ENC[AES256_GCM,data:lTILnGTYfe4ZrkpLdwo61PU3w/LNbh2Mp1cxrdRCcG9+gTe7PUXuI+ctiaefuZ9qCkKdqpLmmyrhEwwka9qajk6JJhECZPUB6gw/ctx5pqpKxli/uXdTGIcqYmlzNxtng3rTF3lTn2RLNlQGll/lBqHckpdsOVWA6jBOf0uRm0s=,iv:lRRlKbZLMkmRxHr/xiiXhzIPeUK1tVTleY1TpenKKLg=,tag:iu5BT1byQC29pP1J+PRFTQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
