---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nest-rtsp
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: jakguru/nest-rtsp
      tag: stable
    env:
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 3000
          rtsp:
            port: 554
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.home.arpa/enabled: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.home.arpa/enabled: "true"
          # auth.home.arpa/enabled: "true"
        hosts:
          - host: &host nrtsp.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: nest-rtsp-tls
    securityContext:
      privileged: true
    # volumeClaimTemplates:
    #   - name: config
    #     mountPath: /config
    #     accessMode: ReadWriteOnce
    #     size: 1Gi
    #     storageClass: ceph-block

    resources:
      requests:
        cpu: 20m
        memory: 300Mi
      limits:
        cpu: 0.5
        memory: 500Mi
