apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: default
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:ZXZoUCaGoOPFAqIw99EGLWhZj5k8//ihc8HP1r9o48c=,iv:euv2chZaT81zqnqImXyYFZaO6d+f8Fkl6S0gl0ITnUA=,tag:CCXkCIuaGz3OOP/vqoMxWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNnVycEhPVWcwSEN1Y3dU
            dFJ1QTJyeXRHQlp3SWFEYVhNSytLdzZjemxnCjVOTEpTS2xSeG8yL0pEcklJYk51
            aW1TVGtDNFcxZ3VOdnhhUDlOMVhIRXcKLS0tIGpxeERJeFVmK1JONThjUkNwaWRs
            WTlZN3JFZ2tKYzRBQitMZllIT3lMMnMKs1qkSYiTCIjsyCAOls/lZMobUIyS6fRQ
            Q7eagINn6XYWX2BnePk6Vix/2cTs9h71j9Ts4rjkcfikgKgF1NiUdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T08:47:05Z"
    mac: ENC[AES256_GCM,data:JhNr0ZDBsUuWsnW5DDrbeOsH8oizHfW4TXX5QSImtib6jmOWynh18U5zN1V2zVD21CIGAXCsH1+yL0iartCkp4MoSfUXjb98wNE+qHRdIhxlU+Pa/SFMP5iqL2KhWVi60OkbcF+OmF1N1cejQrMAsA9gTPcMEloU7vbzWH4sR8U=,iv:3yUxHrDFxKlqlmxO6kHTxaaqxtQQhv2++p6DUH9YkDU=,tag:NbQzvmiqLADTDfvlDsoGZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
