---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: local-path-provisioner
      namespace: storage
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.20
            command:
              - "/bin/sh"
              - "-c"
            args:
              - cp /tmp/secret/* /mosquitto/external_config/;
                mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd;
                chmod 0600 /mosquitto/external_config/mosquitto_pwd;

        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.20
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 10M
              limits:
                memory: 10M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: mosquitto
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mosquitto.${SECRET_DOMAIN}
          io.cilium/lb-ipam-ips: ${MQTT_LB_IP}
        externalTrafficPolicy: Cluster
        ports:
          mqtt:
            enabled: true
            port: 1883
    persistence:
      data:
        existingClaim: mosquitto-data
        advancedMounts:
          mosquitto:
            app:
              - path: /data
      mosquitto-configfile:
        type: configMap
        name: mosquitto-configmap
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
      mosquitto-secret:
        type: secret
        name: mosquitto-secret
        advancedMounts:
          mosquitto:
            init-config:
              - path: /tmp/secret
      mosquitto-externalconfig:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config
