---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: emqx
      namespace: default
    - name: postgres
      namespace: default
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.5.2@sha256:1dbc2bad3e974fe4c912f4ce602c2b418d791cc8525c2aa5fed5a7a289053df7
    env:
      TZ: "${TIMEZONE}"
      POSTGRES_HOST: postgres-rw.default.svc.cluster.local
      POSTGRES_DB: home_assistant
      HOME_ASSISTANT__HACS_INSTALL: "true"
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${HOME_ASSISTANT_SVC_IP}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "hass.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: hass-tls
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    persistence:
      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nfs1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/k3sCluster/Apps/External/Backups/home_assistant
        mountPath: /config/backups
        accessMode: ReadWriteOnce
        size: 1M
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
