apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:crkQX2HeOKRLWH1IoSiWYSbzSG1ggVXl/hZZxaA0gFiBTl5Cef9dXA==,iv:smNDUrxtu+HZ+2ZJeiyvlGrOyFbwzxyb7hbUnNVSyuk=,tag:2GWF26pBsj7IjqRJrc3Onw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSWJhZGxXd0czK2tzcy9o
            MTdKak1OSlRUR2h5VndEeURBTzFwZlBSNnpNCkVQWVJpMndLUnpVSmhQZVVqRE9p
            ZFlCVGoxbXFtd3JTQ2ZBYmJ0L1VoUmsKLS0tIFlpeURtS0VJMnJOd2JweFJiV2Iy
            UEpjNmhzWmdNRWVkMmIyQUVhTVNHK28KBKTEon1QLKeCjPWjBYbDV4jYJzL0lBis
            BTMEKNGi5duM8h+NibARwm6h6Wf0jJhPLcAF/jIqNWg8qFmZOZxYxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T05:39:52Z"
    mac: ENC[AES256_GCM,data:dQ67ZO6osXwRGdf8cV5+6uyMoKTnLGQhfgPnCLge6qAZEndImfNg/FdPwLd51zrVgrPBR/tPwO+bSNDXAEmGeXk3qRuzZshhSPJZiVhtO1CtroCGylpBXMCRuclrW6vDYG/CszzBtxlL0sWa2p1Re9tq3koA8U/zX9fq73pq03k=,iv:bRBlQ2F4xQaZ2IT6AB/2HktaK6iN52sJ6CT9LJyEf8g=,tag:PVrprLAgUzaAp86PiN9/pA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
