---
kubernetes:
  children:
    master:
      hosts:
        k3s-node-0:
          ansible_host: 192.168.16.100
          rook_devices:
            - /dev/sdb
    worker:
      hosts:
        k3s-node-1:
          ansible_host: 192.168.16.101
          rook_devices:
            - /dev/sdb
        k3s-node-2:
          ansible_host: 192.168.16.102
          rook_devices:
            - /dev/sdb
        k3s-node-3:
          ansible_host: 192.168.16.103
        k3s-node-4:
          ansible_host: 192.168.16.104
          rook_devices:
            - /dev/sdb
        k3s-node-5:
          ansible_host: 192.168.16.105
