---
kubernetes:
  children:
    master:
      hosts:
        k3s-node-0:
          ansible_host: 192.168.16.100
    worker:
      hosts:
        k3s-node-1:
          ansible_host: 192.168.16.101
        k3s-node-2:
          ansible_host: 192.168.16.102