# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:M98XxB4zqnuv1i26kZQ=,iv:lCQy01K7oAsV33qeVBh5ezHX8qQBaaSISyc0GGw1u0Q=,tag:5/dK5SZFdVfSSh74d6JqDA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:pB9LjPO+InX2fDbQmpNPm8dN,iv:ZLkaulnKOGKwoczvKy3ccpsRDvchBELy0lKvwBN5XO0=,tag:Ul/Sw0bsW2S5HHgWJdAU0w==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:w92N6HQT8+U=,iv:hgcRkWnjhe3+dEVuaue6YWSxKGC+l+DwjaZi3T3Mk9o=,tag:ZjZ4AegEc9BzJ+GBH8wz/g==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:b7ebzQ7CjMw38A9x2vUEd3LW,iv:kAzPM7Nm0klNg0WV82VZw9edcu3G5IWVJfVmJzQnR8Y=,tag:XFZxLAYYj0cSMeP1178ciQ==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:PdxAqZXb/cWYFqtq0q3x0+vFO0BgTjbuqhAs,iv:vAjTuyHo3yS5CEM9vtm8sQHa3udEOMhcHFAmTOLJnwA=,tag:dRJe/qcKC2lCGrASCdmcuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U0hjTjdYUmlaT3MxRThr
            ZDRQbys3RTd2MDVEQ0hBMVR0dXJ4RnBlbDJFCm0vS2wwUGFuU2lUcVR0T1hvZWhp
            Q0lEOUVPdklMQjVaeVZIenUzRXMrOW8KLS0tIHloMWwwMnVNY0VhNm4xSWZsZ3V5
            NFdxYmx4RmVaeVR3Wlk0ZTRCam1mSG8Ku/ZJ4mvPs55mknym8M8nXp81r2gGZrdG
            e4XJflYciGyi9lb/EunpE3/hI+D/eGR2xQ8dWXuxF7d2ujy0bxLj/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-21T23:48:28Z"
    mac: ENC[AES256_GCM,data:UjyMEr1KqOjtJ8yccpAEduScMfCLGA5/gp4talxsVN4lo28/15PiV65O7PaNMJviJH9JrU4d3GkKbP4WJM4I4xgNNO+s51tmGZmiAl6w81hdq2c55mTR7LS+toyj+9UMKUAd9+5xq+/gZWkCbEG4LPr2tSWzxkomNPfKyBey7I8=,iv:KZHQmWHW8U3dKni9XfNhGPOg0bAayrjgptwGkRO7Ne8=,tag:CM6cbIRBiqmCh5KWPlOVPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
