---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: k8s-gateway
    domain: ${SECRET_PUBLIC_DOMAIN}
    ttl: 1
    service:
      type: LoadBalancer
      externalIPs:
        - ${K8S_GATEWAY_SVC_IP}
      externalTrafficPolicy: Local
      port: 53
