# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: esphome-secret
    namespace: home-automation
stringData:
    secrets.yaml: ENC[AES256_GCM,data:CEQetW5wjN7rGX8eMd+Rvn7FrWulLn3T5u7liVLpfOMJSvC3FklF2QR4JjAkn/cdJRWGGIBic/EnbH0RT1cX/IRY7puz/c/aa7sDlqDp/vO6+SjGrxNPYCoFZGDUJMCfawhUmtp9cT3756WFBJbpUVk1eewLCXflABtQjXMl0R+L2eIi80wsUkAqyCJPJNpuWkVJylPT4Z6t1pNc35PAW7z7Ua5OsfBqv4Xn6ZFN5kpZf4pCawkI,iv:KMA3Rsbs7FcwqTez1KmANld+HzUDwx+tCJa9AmrmPgU=,tag:d1gim+OhBIZV56Q2FFsCmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdDlObXlyOVBsckEyRXBt
            TFBqcExobXFZZmVvODl3SjJzeHAwcnNyTFVJCnZ1L1V6bWtPdUovYVgvVjNQdVRn
            NDdOR2RrejdDRzBNZW1aRjM4dFZkNFEKLS0tIHNCaEYwZzZ2aWJqMkFUZFUxY1F2
            Q3Ewd3hBS3FVUlNENzQ3NCtodnNyT3cKQ/TMRrWHthh6KArTvkzTU/7Z4odudnI4
            kH8GmqdhOK6LfMtgPzAGovhb9bKBix7AvuWa4zycahI7YjInzb204A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T09:27:42Z"
    mac: ENC[AES256_GCM,data:NnT5xUWR4VA1vX6WrIQTHBR4eUnq4alpFyLLWLbSUyPSibuoxnHrmyGwbnvHevNXpi447OwqFIEw5nG7mWegDKH+V77lA3pjW8OwUJVGCtBGsx55u4AHwDQQB7EUJpHYu/L54pLF55P4elVCezSMVqa/Ot1EENC9FlT8bXbSS0c=,iv:2v6O/eoRRLSEum7O0XJnbON76lk+aCdL1vRr9Sf0JR0=,tag:VRNb6iE3EMJnV5zzB/vlTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
