# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: esphome-secrets
    namespace: home-automation
stringData:
    secrets.yaml: ENC[AES256_GCM,data:js5AGWTwDPtOq4dhoeZISdJjPNFZ0JL0FO5QxqnQ/TMRXM6vxnLpv4bXz/m5GclvddXazTFXWktYQ/TWGOIAqKu9iUgOm4QKbTi1WUNXim/+N9GAd8gi3nTB+1pW/YYVOFn0B8RvPlEy/qbI58QwYBxFufS0XZ0qVbfoy0B6IWGp9yc2KoKhSxYSVcnPVZYqbHZX/wGOkqyHOjVQ2DTkuZ9z+DB1JWVDrMk/h39Xl1ZzBaTHsHaZ,iv:tgyZgare+AT9L2pi9Z3zS3K0aMA0mBmYy2b66CgDBEM=,tag://oIvT56ujqUzJ4tsk/PuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdDlObXlyOVBsckEyRXBt
            TFBqcExobXFZZmVvODl3SjJzeHAwcnNyTFVJCnZ1L1V6bWtPdUovYVgvVjNQdVRn
            NDdOR2RrejdDRzBNZW1aRjM4dFZkNFEKLS0tIHNCaEYwZzZ2aWJqMkFUZFUxY1F2
            Q3Ewd3hBS3FVUlNENzQ3NCtodnNyT3cKQ/TMRrWHthh6KArTvkzTU/7Z4odudnI4
            kH8GmqdhOK6LfMtgPzAGovhb9bKBix7AvuWa4zycahI7YjInzb204A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T14:14:35Z"
    mac: ENC[AES256_GCM,data:HQlloSFgSiTPhWtiFEOcOF4hREuDhmhdgeb+oFuFuKz7V8R/RylBN55O+I86BpBjxeizzNQZ94loFS+McOlUESEwmP8005lUkuGP+FYc1HfqF3/5djzRVFJGZktlr8oqblBOWX7bW/IaHhRwKnmGwfLZY0qi2qr6qcXThr4cg7A=,iv:wA2xTnr1iuFvtIQP0o6p+lWCbG/vaTVpuYCAcLupVWA=,tag:sic/cXZHm07eXV/SS5+6Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
