# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: esphome-secret
    namespace: home-automation
Data:
    secrets.yaml: |-
        wifi_ssid: "MyWrlessHA_24"
        wifi_pwd: "Z@nd3r01"
        wifi_fallback_ssid_password: "Z@nd3r01"
        mqtt_host: mqtt.home.lan
        mqtt_user: "HAMQTT_USER"
        mqtt_pwd: "Z@nd3r01"
        domain_devices: home.lan
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdDlObXlyOVBsckEyRXBt
            TFBqcExobXFZZmVvODl3SjJzeHAwcnNyTFVJCnZ1L1V6bWtPdUovYVgvVjNQdVRn
            NDdOR2RrejdDRzBNZW1aRjM4dFZkNFEKLS0tIHNCaEYwZzZ2aWJqMkFUZFUxY1F2
            Q3Ewd3hBS3FVUlNENzQ3NCtodnNyT3cKQ/TMRrWHthh6KArTvkzTU/7Z4odudnI4
            kH8GmqdhOK6LfMtgPzAGovhb9bKBix7AvuWa4zycahI7YjInzb204A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T09:35:01Z"
    mac: ENC[AES256_GCM,data:vXgFXxeiPb68Xfd8hMJHfh7EZ7kpSXVIuAKZZ0gKxqikqLuK3e4ybMXqKK77ng5aWKM/l3iLLMdU9gGacpwGVY7k2Wez/3OLiz+jswvlCQZTlsh0ThCX1nL+OW5Qlq26aYzHlGNXFG7UJmTcwqeCLcF1+gQ3MSOKZk21lJZOukY=,iv:T4cf9pEd8/hIAHrL4aDbLiTh7TxCPeadTcC6pYirFRw=,tag:WSLufiLwNW1y4G3b3q7sQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
