# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    #ENC[AES256_GCM,data:hTy6EiSWEsIjVTuVqePxtdMW0VygVnJez5lHNJ+/peZTz38Xen073dM=,iv:Sz82l1CyDPMN+YoWAznRggdMiW9vsHKzv05I3jUCauQ=,tag:PZCm7raHkhi1yoeu9xjAfA==,type:comment]
    #ENC[AES256_GCM,data:8a77R1/x7Fb7MSuFDetBVWhnAN6ug2z3L3b9ukxp2qTDANgI/A==,iv:80ElOH0D35lAZNxPrf2TEgIY+plcjGGh47lJ3BbUDMQ=,tag:WjZF/pFiWP3iMdAH/fT5aw==,type:comment]
    #ENC[AES256_GCM,data:SOHDI8I+HpBM23iXqRv56N5AQNhIk3kopLFSTH8yQHOfiFzMAdexz2pj,iv:XEEyhBOBaZ9WBKk2+8zKV5Euof1UKAs1eiR8Xi273/4=,tag:47XtXb7ueQmikV4XkZSv7A==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:qIJbjngw6/WHdGw=,iv:0yQrsQpBP36g+nMFrxBvBaYxIuG3OGx3DJUVD/9KC14=,tag:Ik7CVUf9s2yUNPPBcQNOJQ==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:Q0KddmOj/D4=,iv:5UX4/C5KxmQLssNn7iHfsqufTv1JDwZPBzNPhnqsIik=,tag:yP5c83C6Pj4LmsaVLQt0og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeG5HOVJyS3EvWmJrcEFv
            VDE5cFFCYjlER3Z2aHFDR05NaWxZVlNyUEZnCnhXQmZ6WnNjN2NjSm11UFFxdWd0
            Um4yd2xzbjd0Q1pOOHRjdmlYSVdleG8KLS0tIG9HbHRybXFwZUdDOWpOckhzZ3BC
            bGtkQ1ZQQTRiRFVMTVpncXRTUWpSem8KGcjqo/FU5n5UYBI3f5DuRgS5xO3grAsx
            0KDiGYZ1IsdLyskBmVvK86V2hjsa051l2JHtmCj5IYNqDpoaCY3xkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T11:10:23Z"
    mac: ENC[AES256_GCM,data:6/nDIREF0ybCnVhUdDSEkem+mso8LUzvvlxyAuVqaWjFMktr56j8RtCjDyxXiDNcR5pcAVbg4/sTHxv7/NY8IAbHg1FVi6H44YraojWit/oCpXP7XavS6nwDIkGz9426AgUT0XRF8IZfBHB5hDelg2ZCu6/VC99jxnG1Z0sfVIk=,iv:CrsyvAWgQ+FtEsf/EyyLW3GQGnqa/l/QsDGXux0VF8I=,tag:Pg6ixG6N4SZCHqUQXhM3Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
