apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ALnjH3+iB1QPgAEoSJBLL4Lk1S85w9T1EZKVcatYtc9NeQHmSiVvZg==,iv:Wz6TW3P/4jpVJELaNmRaCW24Wdu2v2IVXSQ8vBDPGXc=,tag:VcovOFzZTRprEMxX5Nozdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUCs4eVlWTFRLWUgwZVF0
            Y3lLZGtoNU9jdTZraE52T3VyT2N3N1ppMXhzCllEeld3dWIyMUVxRmNXMnpraDA2
            dHo2ZlNxVzk4c1BmY09GM3NFSmtzcTAKLS0tIElGNmVZTGJIM1cvME4zM3hTYklw
            SHN4UUtyVVVNYVk4U0hpNjlQTDR6T1UK16iEGd+i1LUPmA0gIBziQkpoNL9UrfrL
            +cth9Hc6FjP6p+Mne+peGPXi5fZuiMeXW2B4r8b6YES5SFiCtNLFlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T11:28:07Z"
    mac: ENC[AES256_GCM,data:8GvRltJm/4dQABOk5fHm0DOKhdEfYKVfTcMXquDXQQWxYDGDxNUrD+kXw6xCl/C0zQ1adKLhRXPfd/I16t3qLl4CgybR7AqlazHEoUm26X+tMXM7+uirPqrto7f83T68e5Bg0i4Zzr6OdDqVldmnpJt9u30i6910KUqJcVgKjCY=,iv:04ggnbFjilisBYSL0IvnbUpjXgj8cI4IuT6lkStxSS4=,tag:tDK6PI0x869unWmJDbdscA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
