apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:iIcWDhpLF8ZFyIo4VXAmz28MAwoVflZL2EKqISqreZtoFxiLnInKLw==,iv:QVa8+CC2NAFbDA9RyA2USPctfRgHLVaFvgOqAdHjMRM=,tag:xkJtY0qwnKTiSzcFxW23hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSkJCNnIxcWNpT2E0Z1VH
            a05uM053aGxZclZGSm5MRnN1Q2dSNUwrS2hNCkpsWGRsdEZDa3lMS0g3OEVwSFBt
            eUxwODQ1bW41MFpna3B2elViQk9SMTQKLS0tIDU4Y1g5UklialVFbkNnNTZzYmxV
            TGRnT2RCZmUxNWVQVkp2ays4L0plWWcKK520VW3UgEgXrGRDU3Bq0gGFVM3ea8RE
            BeZfmFV/zPh/FiBknHd7s5Mu8Uqlwqms+NIoadZsP7bjzLGbduzFDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:06:10Z"
    mac: ENC[AES256_GCM,data:lBP20q25oOvf9Ubfi8mkf1AlTbwVfaPH4ZlYog/x9htB5UQl5V8nUnr1OZ8NLOAoJ/u+lmJqobg1mRpbdGYvT9b49ObxA3c04oRsYtfYkYq1/tgdqf5HrW+izrpIMtMqCB1dUy5Dq8L2jF7BXWWIhiXGgqtdGt8OX1lWqtyjSB0=,iv:Idgs++KomIKTeljCfhB8kWgmWfmHs0o7iez1UPA8CoY=,tag:LZY0FUQx5/c1IH90ALZZ9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
