apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0GfajTHCeeUbnDyyKoUS6KirCjvQ7xsBigvv0hIRUQ8itrxyyzMNbA==,iv:tRtYoxb+gKG45tW/dnw9CS2/Sz7cG3p+OUfZRg93ABU=,tag:MSZf0ssMHe8laGWdl6RNKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcm04Z3FTbHAvaHlBWkJR
            K2J2YjltdUFVbFNtUzRRUGpPUVFTRjNUeTFRCkVGdWZDT3hxZ0JrdDdSWWxCUExj
            VFh6dUx6bnd5dUkrVnF6NEtkT2J6YWcKLS0tIEFNNGVmTmV6THl3aEFWOG9nK2pP
            anJJM0dJYnBKMndjeUgreDVwQlUxQ1EKWb+H0N93NELs/0m7rDpex2yonUgSpLhL
            josCYq2RHRcy1v3n1k+riXj+SO3A8v7zDn0Umd6fdU7/+nCtvnVH/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:33:14Z"
    mac: ENC[AES256_GCM,data:7bKT++Sj1RUXo/LQYK9rFDfnBcY9nip361IiMBd4TGUSJTTmJWbhavAWGQGhxoJMfRwhxAnSeWoNG7hk62aiwU18GNwFnO+W7tWsFnubrIIxPxfQedeDcYcVq3quoETLr3rkvT4ubfd9//I6IwriOhr5At/L6+GLN0X7pi9cN+o=,iv:vL+EHmaMIZSMnkU//By3SfF4xFxY2BXboMhSQFEAGbw=,tag:ceVgxUitpCqoAjjiRmL83g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
