kind: Secret
ansible_user: ENC[AES256_GCM,data:HO4jmvM7,iv:UlLSekBA88LBQEnDjR4aN2+IzXyGA0ItD1EzgPT9v70=,tag:HQFKpVOxSk26B6RQtAYH/A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:i4Rm1UJUvA4G37bY,iv:NJoTE4Aanh0VZlPubamsMwzJoHdK7Ayn8O59xwaV3jo=,tag:5YuEuqQUdSpvRXHgzer8Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd3BWdEt0M3FoQ0QrTGFr
            bE42U1ZUUXBoSmVIcXo2MitUNEo5cllUOEZzCllxYm1SR1dMMFg3NVNiZ2RxSU11
            eUlpZW1EdVc0UTY5TUo3WXd5RDVOeW8KLS0tIEZSVmRpazRwMDVpVUlVRHRRbFZo
            aEtiQVdLRzFkbGlIMlpRc3FpY001SlkKuxhcnrKhuafiQgScNUIaKJ1gREItFKa5
            Rz62Rm09a7GhSHVNnvAmFlKyTTOdneWvVYNeXAyjGuNmy/7yDxS/WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-11T06:45:15Z"
    mac: ENC[AES256_GCM,data:4zyf9ysT6S/ht4LpUEYoaPxuqhy7cNSeNRWrvkAmyArGP0HR5jAZOYxpwRDlMkjKjulkvAPySAr/I/Y8D4F1VIHu8W757ZAm77eBsiEuRMPHLgIL0/+eXCAvEu1leMQXICByF8/cwPMsyamnTDywvjrmYGGbYqO6uX3/azcmaps=,iv:XKgl3xG9aQE6i16mf0b7LSVykeI62JWQOJYSn9Q1tQ0=,tag:nR/z2qcoVV86FBmREXlRsw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
