apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:xPU5/+Rz/otkzqOUn4zylgKgzplAUW7PsiPtoVl0iQuVWcCQHZXRJA==,iv:XUQ2IKmGVYADVcroLTtpnWfvMPLaIDWFWPOjftlzC3o=,tag:E+sukzLSJwXJ52u/b/Jkhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UURSVjFRcGV2VkcwZDlP
            SFZZTEhUZys1T0dvS1pEdmE5L2dPTGNFVTBZCk9GdVE5ellkMkZmWWgxc3JjbVdm
            Qk90Nmx1cWdUWlB2dXNjMFdXc3loZ28KLS0tIERxTXZnM3IvakxZcHFaTE94QWh0
            SDB0dU5VS2YrV2UzbU5Gc0tuTjFJZlkKtycdU8La3sMK0P8ersPeUJ1gj/IgefYm
            RhRUkqH8hBh0w+coyPMvIJl2toEX5zncabPsWgzqqykwITyoq9xV+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:02:02Z"
    mac: ENC[AES256_GCM,data:9S+anE8bN9hAszMsSBFTJ+nlGuz+tPVpyvEZXHKeIjwVvHt2DeB3+cq47PUqEN1zd91cCjB9nLRorxd3N8RdgAyCyN6ftkHv0PUUoa0gLqgzteDmOK7CYqRMESKfuRctx+z4HtNv9dzokL0X89EthOdFwqmlExoFSnZwABiXZHs=,iv:4mWscaNemFXkKHk/Njtlfml+H9SszIHoQ7e4bBnhKlg=,tag:FbjMMrWo+NICPLeIerHm1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
