---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wyoming-piper
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: rhasspy/wyoming-piper
      tag: 1.3.2@sha256:42a2a402e6c21e8b9460db76ef367d621eb16878f5fb1c66626c699f30ca034a
    args: ["--voice", "en_GB-semaine-medium"]
    service:
      main:
        ports:
          http:
            # -- Enables or disables the port
            enabled: true

            # -- Make this the primary port (used in probes, notes, etc...)
            # If there is more than 1 service, make sure that only 1 port is marked as primary.
            primary: true

            # -- The port number
            port: 10200

            # -- Port protocol.
            # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
            # HTTPS and HTTPS spawn a TCP service and get used for internal URL and name generation
            protocol: HTTP

            # -- Specify a service targetPort if you wish to differ the service port from the application port.
            # If `targetPort` is specified, this port number is used in the container definition instead of
            # the `port` value. Therefore named ports are not supported for this field.
            targetPort: 10200
    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: ceph-block

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
