---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./mosquito/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./ zave-js-ui/ks.yaml

