---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: golift/unifi-poller
      tag: 2.1.3
    env:
      UP_UNIFI_DEFAULT_URL: nas.${PRIVATE_DOMAIN}:8443
      UP_INFLUXDB_DISABLE: true
    envFrom:
      - secretRef:
          name: unifi-poller-credentials
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    resources:
      requests:
        cpu: 300m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 200Mi
