---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: golift/unifi-poller
      tag: 2.1.3
    env:
      UP_UNIFI_DEFAULT_URL: " https://nas.${SECRET_PRIVATE_DOMAIN}:8443"
      UP_INFLUXDB_DISABLE: true
    envFrom:
      - secretRef:
          name: unifi-poller-credentials
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9130
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    resources:
      requests:
        cpu: 300m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 200Mi
