# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unifi-poller-credentials
    namespace: monitoring
stringData:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:OfJELTYd,iv:dTJtZux9rPjtwb5VzqGeIUNkn+jttc/OKV4olRp0B4I=,tag:JPeV3dgXLbyKgY5eNvE1Ww==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:Ek322bpXLMs=,iv:GouaONNeqq+aXCmZ2Qe9TyWNnj7Yo1bEOUUa0RT3oew=,tag:DAfBxcgZvedMGBlqRxiIpw==,type:str]
    UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:lQ/yyGtByVmS2XPaveTAibnhbq6hY+VAAg==,iv:Wy7Tg68+NJOY1rqCkGFzfAbgj7qQBwc48vHrQsA4yx4=,tag:LWCwAvR63XE+GKtBQYNU0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZG5taDZNRzVZRDNHUVBm
            NEpoOGRSZDZqR1JkTkJRVnY3bWZHQnRLTlZjCktoa2dxcGg4T3pJbGI0VWpiakpv
            ZG94Zm9LalVnNzdvb0YvYlE4dm5hdEUKLS0tIFptcTdnYU40VGxINm05SlNFdG1E
            UXB2WWNlSkk5eEpzbmRoeWJ1dTBSN1UK2HHKMeJxG8ji/cxuof+G90F6xAYjJWAG
            s6hOnY570jNuZuLjCDqeft6IjidKSyhfNciS2P5RAG2Aq6+S3yMAjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-05T12:45:36Z"
    mac: ENC[AES256_GCM,data:TpYSXXQ+315NEg5zCbeKbKIyrEp+DSmqNBg7TmU0RXHhUl1Xl5hBhsQ7ttDCEXdoiJlcYUxhgGKw72BlnTKQuv0mDnIDxUI/e8WVt4El91Xt1tjosIaJbHWDinNgMmUs3KBVXxo1TZzT5GOJ5YnoEY30aXe3jlLmp+49+F+UAdc=,iv:RI9K9yVB7lm1XLpocfSfxW9mT5K426zcz7OkCAD230U=,tag:VCntgBFU5a1mn8AyP1vlXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
