---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app enphase2mqtt
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: emqx
      namespace: default
  values:
    image:
      repository: ghcr.io/dkw99/enphase2mqtt
      tag: rolling@sha256:4e72ffc981d684fc87b676c0fc57813c45ee05b36f65b8d81887a45826c71026
    service:
      main:
        enabled: false
    env:
      ENPHASE2MQTT__ENVOY_HOST: envoy.${SECRET_PRIVATE_DOMAIN}
      ENPHASE2MQTT__MQTT_HOST: emqx.default.svc.cluster.local
    envFrom:
      - secretRef:
          name: *app
    securityContext:
      privileged: true
