---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
