---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: &app default
spec:
  interval: 15m
  chart:
    spec:
      chart: pgadmin4
      version: 1.13.6
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  values:
    image:
      repository: dpage/pgadmin4
      tag: "6.15"
    strategy:
      type: Recreate
    envFrom:
      - secretRef:
          name: *app
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - host: &host pgadmin.${SECRET_PUBLIC_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          # secretName: "pgadmin-tls"
    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config-v1
