---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: pgadmin4
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  values:
    image:
      repository: dpage/pgadmin4
      tag: "6.15"
    strategy:
      type: Recreate
    env:
      email: ${SECRET_PGADMIN_EMAIL}
      password: ${SECRET_PGADMIN_PASSWORD}
    ingress:
      enabled: true
      ingressClassName: "nginx"
      # annotations:
      #   cert-manager.home.arpa/enabled: "true"
      hosts:
        - host: &host pgadmin.${SECRET_PUBLIC_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          # secretName: "pgadmin-tls"
    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config-v1
