apiVersion: v1
kind: Secret
metadata:
    name: pgadmin
    namespace: default
stringData:
    PGADMIM_DEFAULT_EMAIL: ENC[AES256_GCM,data:Jn4lT94QnmcBVqWuj45tXsXf,iv:eMc6GZ6GVBWrIycldHRciuE/jXhZ15gKNUu0RK1w7ek=,tag:ED0/xo7H7MVdzhSQ/Pqhow==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:c365ZUomcYrKycYmw37DCNbwqiXt8pst4P6x,iv:FLoX0N4Oy7BshIQDW8myb6oAsO4vn/JfpIQv1KBdiBk=,tag:FVW/NMv1c4b6XiXxyUabcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQmJMY1I2c1g1NGtsTWU4
            TVRKcTVrMTRsQXVMMnkzYTJtejNqMnpIWWxjCjF4Zi81Z202Y0Q4ZHJMQXdkUy9P
            engwNU5MMHRMclF3WW15RXVRcjRDVW8KLS0tIDNkK0tiZkJTMFdpMThMZEV1UFFR
            U0ZQNVA0eUVjSklWSVhKOHFHVzNXYTAKMT9IF/PwG5168fF6060C7wCf9ZJAGOCq
            HgK9gDZAu5a/fNPrBdumuWyYhoYlkNmj42d1amDNqin2DcbrON7qJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T12:07:23Z"
    mac: ENC[AES256_GCM,data:7ibMGNwb1nPNkts2jWCgj/7vZ50m1Jiw+eyCwPzsG2ug4u8CjlWBY//jMwLg1ZV+F88Ch+5cYgGBNuvn3I0lw7CmyDmL3rxGv5z0h360FoJsJJevIvVLf6m/TlnqyFzwQiqA+SRorylSS5sFLKTqmc/GwyhZgM+/kSZ/lDfUrQo=,iv:HIXQgj+76bZhpQaeTN2VCOgWxp+U9ywGt2GcfNommE0=,tag:TCxgZ7VsQmqAEsRm9mXRMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
