# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: default
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:NgVg++4WXtkButMRl1q6,iv:6ubLuoKKEHjpLDAuwGS5qXQVQ0EXMnFM9P6fpTgM/KA=,tag:Xp8+jb2R5L9oGegocqU+RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb2x0Zzd1UnF1R2RoMVFn
            Z28ybC93UDJVcXhqeG85WmNpU0p0ejRWV1Q4Cm5WZWZudVcwN0krU1FSSm9Xd3Nu
            cytmZlpyQTc0emZxVE55TTBISnMwZTgKLS0tIEVjbFEwTkVOZnpvTVdUbWFkLzh5
            V09VZ2NPWnR1REtneUZ0MU1IZExNdFkKDO1fXyvdPICl4Qdl+CoO4m1LyHYigdtO
            tB7zVvMiEC29MlQB5luUIhTrCfGaC+Yl8krIybMQC7Q1PxYZCZmKdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T12:29:28Z"
    mac: ENC[AES256_GCM,data:yyrJr7dN7LZrzlyLjVl9VkobCouuLyBAFMwBAX7NZxFEYG3AzHsoLL6nLkj/QF7sG1HC1XWpRWlDKYV29rXapWleh9nLrqDLWaYVqyAT2KAQ6eVuBIterewULtHng6nuwIkEibW7ag32StcgXZLCIQ2qOZ02oNTJX6+/YBFjO2g=,iv:uU8vwu8dIF7TWR18AfM/EHX+Im60XoENuwpN39GnL6s=,tag:6Rk5loMc7GsdO2rhyGlzeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
