---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      VAULT_ADDR: http://external-vault.default.svc.cluster.local:8200
      METRICS_PORT: 3001
      POLLER_INTERVAL_MILLISECONDS: 10000
      WATCH_TIMEOUT: 60000
      WATCHED_NAMESPACES: ""  # Comma separated list of namespaces, empty or unset means ALL namespaces.
      LOG_LEVEL: info
      LOG_MESSAGE_KEY: "msg"
    installCRDs: true
    replicaCount: 3
    leaderElect: true
    serviceMonitor:
      enabled: true
    webhook:
      serviceMonitor:
        enabled: true
    certController:
      serviceMonitor:
        enabled: true
