---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.5@sha256:30dffe7ad04ea0e39db0b50c0bd5e79362f99f7ff6b250526d2f389b58d96f14
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.home.arpa/enabled: "true"
          cert-manager.home.arpa/enabled: "true"
        hosts:
          - host: &host qb.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: qb-tls
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    persistence:
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nfs1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/Media
        readOnly: false
        accessMode: ReadWriteOnce
        size: 1Mi
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nfs1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/Downloads
        mountPath: /config/Downloads
        readOnly: false
        accessMode: ReadWriteOnce
        size: 1Mi
    podAnnotations:
      setDownloadGateway: "true"
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        memory: 1Gi
