apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:wc5Bwo+SlW79bLeMWLeOyzCR,iv:nDfJjGswsmNxKPkiob8GywU+OO8lw0F8FeQ4nLkH5Kw=,tag:q9u3xN0Sm98IvSQN9/bA4g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mtAy+GdKS7p7AmQCHdLEBSTN2JOoEWq8y7dxTnBoJL6VSv1O,iv:JqgHYV/1WWW9xeH3nySykdgMCtEt8skkzbwtSDomoZk=,tag:0UDsjiZBIlSfMb2yEPbErA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:scGaPa457TOx1HOLniI=,iv:CUJPPn7rTPLm/fpIf+uPQOFIeyJGWH8K01ikQGdO06k=,tag:JqtiWTchPP9hQcTGRwuKNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENWpVVWl2M0cveW11TzNq
            QjNHUGhoSCtGSG1rNTBQYnVYcmZXYktuMzBnClV3dDFxWmFrK0J4cWxLL1U1YzY1
            SENaUno3bzVhTVE0YlY5R2Qxd1N4SU0KLS0tIENEM25XdmhzekYycDZBeUp5cCtv
            NXhrWWF5SGtKTEovNXVIeTBTQ2dUTFEKv6dFxHBp3cq6c2+Z9l3wGPVkUPG4kB4+
            btnioiqSaSUDTiniIBZ06RA8hoDbwacd6R7WbWlIpWY0rAifwUazRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:52:15Z"
    mac: ENC[AES256_GCM,data:tH+GrB8w6uHbSg06xoDPlG0MHxAjWxIzT/L50KBE6rI1S+KOzP2YZr6oidJNntZbYoS5xVb3lZE/GruFCvji7pBbukvnuJd3hoofIFNG8h3whvIYNgInU2rvwCVREuQn2s6z5gufblg3lTaIgqwiwNCJhdOCy/QO2cTsXaFVedo=,iv:pBZ9eOPN1EmQ5v4g53+7TygOhl3kJii/w9NoVfNrZZo=,tag:aT+ebJCv3dFKW8kwVqqj/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
