apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:dIq/rPHUHggR8rE8Uygbym9Z,iv:HUMsah8tWoU6pckJmeAhAE47owXvQHmw8Hqhv2YSOOo=,tag:sJqly8eUpjrXthFTh1Y3Qg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+9VlpcLtOprXUIcT1rkU/Dd6T5yC5Q5qEPcrxpgAF1+sK8k1,iv:qW6DerWmjHorMgmhNJ/+leJzVTTUnk7c3U+gSCHxk+8=,tag:hWm/SVYoQ0LCIvdy7FpT4Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:sSIzZ4H/UIZHjpZmqQ8=,iv:+OQBboPyEAZMBlr2DrZraHzQR3tQg/9T6D+AkZMioII=,tag:3evHma7qRKkCqD1u09ncow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVHN2WmJhbXBET052Wks5
            NEU1aWxuY2RoaGptcVdwdmhIdXZTaHZpU1JzCkVGb1R2bHdtVU02Zk1qRzRGR2NY
            Tmw1NzgzY0Q3Sld4dkZWbldUMjR3WTQKLS0tIEUwbEh6VUEvVTVRMVMrVjlVZ0VR
            RGphZkliNi9Lek5jNVVUdG5oN0NYbVkK6QO98W89VJV6OSxFnjoFvXeTm51ItqWz
            SXHgpDDWp1DSc1rdF5IRCF+RnkYYXi9S7LvrbLSlYQD0bjc5CzUBeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T08:00:57Z"
    mac: ENC[AES256_GCM,data:jqAeA9ZiX7fo4GPE5ZhJwGfqLTyij6vyUJpcu5zZ2k5LhWciixCdOH5n23FjiCBHmC7jhBGGrKJG/NsHxZOZHA12aFIMTQTvYR4MsMt9zHum/fsq+/TQhsbWzdG2kG5QetvzvrIsv19e2wABaxncdUCX1BpDT3vlsWUdasPsR40=,iv:10FJ8DJUT0e/QOEDDNs5oFyc1N5grucZfeY9zAmh/3Y=,tag:se/MBEnbtmlcewpvPSjrOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
