apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:oyKoJxCoPPwI/7uV5byhYeYv,iv:2Unc3zPIsj7dhdvq99h0kLlBA+fPPzGjJ/Rot4uvFAo=,tag:gC9Be7bnBqIOCsHSMjLlQQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:JENdrQuqqhEx+/08gmbi+3fRjVDvvwY9rQt2+nHWvXeemYZJ,iv:HZCyR/HGKDX3/gp2t1OfizMlwMcutanstzaDCW+eoEE=,tag:m+q7T09+XasCBw9MLXMxlw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:AV0nsZYuwMGCW8IHY60=,iv:t369d/hxpU9lBeYdHSrQYAU1RSPP8vteqPCxsIeb6H0=,tag:ZZWRrsDV5evlw7BwjBAIiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ3pETHd3RFQ4T2h6WnBv
            Ukt6bnFCYjdJSWNzeGFpYlUvZGdzZDNFdFFZCkJMMmhtQlh6elJjdndwd3VaQVlB
            cTc5d2VtdWpMeFVsQ3NnalloVWU0emcKLS0tIDJLZW41WEZyMDYyT2hWNkljVVhq
            cGZyNDZJS2lzb1NvZmhaNVdSS25ZeTAKhiG3WdOicpPYyn+FWuofcd7M1tlIlQSa
            KdmnTHqnj+wNLluuG4v8T8Idyuvej6fASuv9gKnafwqZYSDO044toA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T05:39:52Z"
    mac: ENC[AES256_GCM,data:Awditt7eZCsUawXsVlu/ALKMz+lRzz47jJjWfhd56nXtNQguGiHW1WNNUPMakkYqQaCc5KClE/I/tQx0nxXA+8suEh43cL0mmDoswnT7ntuj4afuqheu91mlR3SDFfprnUnYOe/hZvGXlZMmYrLDc97MpMhWcvLw8iQlHnBCFXI=,iv:pqUR1CIlAaveeAMHmsmQvB/4XwwupZNZMoJKEzoATrE=,tag:xkft0vNAvJoxTTBhgLWP0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
