apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:eouJ3z2b4SRm6SJG,iv:JE89RyjRhyJavBgXcuiuKIarcaUujPUjAzmtrMhn9vQ=,tag:gQxPW6VrQMovWpjAzwKxPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd1JVUVVjeFFNUXRFcS9R
            aXhoYllKMDk4NHNlWlpoZUg5WXlObFNGTGpjCmF3V2RsZVJGdmJmdXdqV1dwRXVj
            YVpVc2o3U1pKT25TZGMvYkdzdWZKcjAKLS0tIHBoaEtyaitYYUhzdVpOV05MSEdl
            dGxtME4weldoMUVvcVVpTFRkS2tDeHcKYQT37KRDveb0HgqdS5qOO4lbpJVDUosK
            YweJf7V0OgRSiG+zQfaYd1gFr1inMaYMhwDqrPmSBqgPMivI4i33pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T10:45:12Z"
    mac: ENC[AES256_GCM,data:5w+tjmzhUD5QSFmn2Zkhl2H2KkM5qH5n9R1cd9tAfzQA4AYzoILp0GvJ8t7K/WQP/3gul3hoMBAarCiOfedXMYzNc0615qXp92AMrNO9dwkahpM7+B2TriBV0IsYL/1XpeRLBAtCeSKfT/l8cEj+7z8OanAJWrwjP/Nmt9oGl+0=,iv:iorKJFwNiR9NR50A4Q+ST0e8i5Mo80OGsZ7Uc51lxzM=,tag:fPH1d2djZKaLXd6cC9YCAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
