apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:yo2DbUj0Snwyt5bW7oFvKoMB,iv:rITfJ+r0+sIxyatn0KNem676vCTZCS/mCKrl/jlr5dE=,tag:TZ0yBp8G6BV+BLA1lsdcqQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:n8Y8TC7GtDIWZV48nlKQfNZPrij9fmYmaV25tuMVpFcOxQuY,iv:oOQ2ZfTUbc0ycW3PPFP67bNAOLrNd0W4+z/lIiBq3dU=,tag:a5ra2Cgy1dyBrrFYVZWJcA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:MnVCS9c4OMVRVUBlZ/g=,iv:9j+ko4oIBVeOuN5LxcWjzVpA+I66Nhjid2329Awb32k=,tag:e0tS7EudlDbXI1ug0TE+fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTW9IR0VmTGhOU3NBbjUz
            RkppRVZaT0VrbmZkcS8yaEVjUit5TGdtS0NnClIwUzIxTUhPODNINzdSY3FFRytY
            U1lldS9oNW1leFZzSjJ6WWhjTkNFYXMKLS0tIE5hRnFZQ2pGZ3lJOEIveDZ4SVFN
            RUg5emJlcUl1V0hVYU9MWm9TY0pFUjQKZkAyruJAPOPRZa1lwv4K5uqNX4/7blRx
            vubT6DUrLMnHtDxNzDbdIKTu3R2sJG9cZZFYlAfNTOm4E7n9SfBSUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:06:10Z"
    mac: ENC[AES256_GCM,data:BYbnyFB2FdBf8KMUjIriDLSsWm4uFsE0FRmP0AUyInQWps14RZlsgiDQJRgJEBJrLKsdf9ZZ7LlYPqDGezeabPGJJkmmmt6mpy0+rA+b3JkIxtWYo5HmDWpTzJsrhNjMy3XY+Icy+ShEm6viSPogTXSo5wzIo/SIHDJuiyOKcDY=,iv:n7xAHyQaT+InyobbdkWAueeD7h4LYrlBs53geL3Kapc=,tag:g4Huwm+iLlcMIAdqWfFYXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
