apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9tDLy2fzB+2kdoUSAlMvkZKK,iv:kRJetiXiQY9xEjhQ005Fx0GQB2tat1hmVmjLspZk9iE=,tag:KtsMJxNGYElLrmnGOqzsEA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:h38beHhBnJKyY9uJWc3pjFwj8ee4CycSuFBdnx2GS9CCGN14,iv:V7R/csyYCwD35mnsC1E1ZqaPIaH40v8qpHJBZ7wZoMM=,tag:o5PnSAG4pH4MlWNKhrgnJw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YFVuk0WOo8jEoqtitGc=,iv:lw7rj6n7hbvXzghoQKwrtG7WGJluA6+oOmHxv2GrDaE=,tag:Bg0dXVmRZOlLTkTOvnxIgw==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:cA6oRO+iiQY=,iv:BWKm7X6DSXcTVd5kq15yYd8bI/P85ijPQxbvXUV5Uks=,tag:WK98BXNokrXpKWoxHc/O6w==,type:str]
    VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:+0gjhkySpDfE0yknNUbeI3F6pBcVr4FOag==,iv:wqsMKwv/RvU+UXhjYe4dZ+PZv8VrwpWEE67YNiAdjpY=,tag:epTvs6r6QxC8/PlnKFxeRg==,type:str]
    VOLSYNC_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:boaQMaP3hg==,iv:JzxebHNFS+83krSKBBdndVDwvEw+rOA64ip+Z3J4s+Y=,tag:vSt9mA4u43ZnqCKQ192QNg==,type:str]
    VOLSYNC_MINIO_SECRET_KEY: ENC[AES256_GCM,data:kfyaGXbGyL6xYLc0UuOplDJ6ncZLAw==,iv:MlyhQvnTXh7bmq/6dhDcmGUd3TdZS38hW6DfKV9XTJk=,tag:0PgHoPUNJmFec/5425ULqg==,type:str]
    VOLSYNC_RESTIC_REPOSITORY: ENC[AES256_GCM,data:K/dMpi7KTAXr5qTzv9IysGC0rNA2g7+HjIdLHZs4sGgMvcw=,iv:tW7e43gTC5kIyOulux8Cuuf5r090HWlUHXUqPiu70tE=,tag:nqX5s4pR1Oo69ZEwmhSOAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMGpOK0ZzQUxoQkJVOHhv
            WDhENitxS2d5SWtweXluejBEQjFYQmxEL3o4CnNyYThGMVVhaEFndndibU1hMWRm
            SEsxVVY0Wk54Y1JYeDZlK3VEV1JnY2MKLS0tIHY0bkxkVlZ1Y2RIWUNGNDdNbHBT
            a0dTRlNadE1WSndhdmF0emFGSWNKNncKaUnqzK9A4kHT//7VXm777MsqzIms6/Q7
            bIQ8ArETHsB8oN1DxKlQZgdhgBfrsFy2UGDdPtgbOhHzZ75J0tbPbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T06:46:09Z"
    mac: ENC[AES256_GCM,data:zX/7ZUoY6rhb3hES1CxrRH3tORGEBZPjCK2wnFLWLSEeFXmUbINKNMTw//ctK8lYiSv4SfObvy23d5J6rmr8dbha/JmJBMtDAB1FdcTlFXmRi6ddjz++E32+gcF1zd5yJ2Ve/jZ0log4LW4Qjvl3sLijyZXJBtVicnUAiAltw1k=,iv:rfBqjuTf/z1HTNakeGn5UC5OIwQSyOoMRbxJnTSRwcQ=,tag:U0et/Gt6f37NoRLLXnf4KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
