apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:TqVXDkU/iK6jQgIN,iv:pekTH/qM7LMcYe50BCWv4H85tGdt41Hj9392PG+970c=,tag:D8zTscgjfnZeIjljSbmf8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSld3RGZvY3JKcitEak52
            c0lCcERIcDU2VVBLaWdGdFVIM0RGT1Q4VVQ4CkUwc2N0Y1RsN3VKUjNuaU50c1Jw
            QW1wcVBWYk0vNWFiV3VFNVB2WU1qRDAKLS0tIDdIWi9jSmkzYi9yb0VwNHdFYTdK
            ZXpuQ1dtaTg5UWJJaGVMUnpyWnNGNnMKPAKakZocETrs5vK9+wNKVkf7e7tIhLTS
            QF/dgu9jGrEeJmBIKAfvcTRp4e4epqGUi6aCVjqZRXH1w4MqVioe2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T08:00:57Z"
    mac: ENC[AES256_GCM,data:viSXw1jOhfWmzMrXnT5YfVa9xu1lcpO0xM6U/nGd8mcl6+ET/Wc19QwtxH4KmBQzZzhJG4QLcbwQDRDcf2nHrzKcHaeq+yp6YFLIkxopiHtxRp/io0oZSgcrndZuXw0l705UQYbezgElcbfiEyVkG1eN2e5Q0ZJsp2pkDb315vY=,iv:gufwSzNSgh1vsixMBdiCJMmx/ubpF5qxVHBTrFre5lg=,tag:kbMojZR1alza0qhAV0sVMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
