---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 3.7.0@sha256:67bba2c3aa9912817eb3aa070bebeb68313d43a4dd7e4912aeba103c9598bd2e
    env:
      TZ: "${TIMEZONE}"
      SABNZBD__PORT: &port 80
      HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.default,
        sabnzbd.default.svc,
        sabnzbd.default.svc.cluster,
        sabnzbd.default.svc.cluster.local,
        sabnzbd.${SECRET_PUBLIC_DOMAIN}
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: *port

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/base/sabnzbd/blackberry-abyss.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.1.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: true
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    persistence:
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nfs1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/Media
        readOnly: false
        accessMode: ReadWriteOnce
        size: 1Mi
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nfs1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/Downloads
        mountPath: /config/Downloads
        readOnly: false
        accessMode: ReadWriteOnce
        size: 1Mi
    resources:
      requests:
        cpu: 200m
        memory: 800Mi
      limits:
        cpu: 1
        memory: 1Gi