# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: default
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:zbNz7Ju+ewlzutVBeLO3ArSIlnCWHK3em9Wo1ZcY56U=,iv:8HiaRV8nIwrVaacoHqtpvyWOLDfxR+8Eh69xO6OZaa4=,tag:kbXXhghOCO1sza5JzG6psg==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:3QX+lcCgyf29UE0KSL2llQpze4W0RZdlAyD2BICWAH8=,iv:nN2WeQyI9dKUTMgfLCKyVnhXho+3ftemJQbPDMuFRYA=,tag:Mo/vggiq/+vrjflLC9jFYg==,type:str]
