---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config-v1
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-hostpath
