---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.503@sha256:3e92a57e143e44f0961bb946d22f28f09f32a83a5009581f58849c1b26339e09
    env:
      TZ: "${TIMEZONE}"
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 80
      SONARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}"
      SONARR__LOG_LEVEL: info
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          #cert-manager.home.arpa/enabled: "true"
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/base/sonarr/blackberry-abyss.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host sonarr.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            # secretName: "{{ .Release.Name }}-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    persistence:
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "NFS1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/Media
        readOnly: false
        accessMode: ReadWriteOnce
        size: 1Mi
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "NFS1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/Downloads
        mountPath: /config/Downloads
        readOnly: false
        accessMode: ReadWriteOnce
        size: 1Mi
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "NFS1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/k3sCluster/Apps/External/Backups/sonarr
        mountPath: /config/Backups
        accessMode: ReadWriteOnce
        readOnly: false
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 200m
        memory: 800Mi
      limits:
        memory: 1Gi
