# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:396v5l1GqrpTWXa68fruxc378FnS4d5I6t0prsZUJhF4uD4SKg==,iv:teQ4LDYavv9ziXZ7wYnzwaJkI73/IGLptG+dk98kT3s=,tag:VabETThL0tXYVVgCd51OGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbWR5SVJwSGxZYjUvcFF4
            Z0tHZElmTXE4ME93VXhFWFFROG1GRWZJUGlZCldYTS9SU1VMUGlBdzM5WkU1OXJm
            M3pabjBEN0dESWFjZnRSUVVTQ2x5VXcKLS0tIDByaGkrTTJXeVBvN3htOXUwaTdv
            TDh4MHpwSG4rdnl0WUFKYm9hdENzVkUKvHCVNvwR9G+60NDAH0Pc03gyojIm7T3D
            Gk93jkh8Muf1YKH1XKGaGG9c74J1JdP9PLO91v3lrUwNXJQKnOcOIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T09:23:53Z"
    mac: ENC[AES256_GCM,data:zf0xEhGT+1GxSjIv22TV96DKlEULlHxEP+CidjKPeATuVbmMjawXCDzzjYbLBUKqQO01lfRnVZtX1z1hh/FnJeXb05p/bODlV6RRZefhQ+Xh8p0BlxTSwm8ERJ9G4k9bPUiXQoVG3wt/RyopYYcnh4S9ZHwX9UMDsLCDMmuoS7I=,iv:bmMiN10JS7A3ybOvojFuZTpHjGiLIOwPYGpC8okwxtY=,tag:doSSTa6DSqJifItssM2tew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
