kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: zigbee2mqtt
    namespace: default
stringData:
    EMQX_USER_USERNAME: ENC[AES256_GCM,data:ugwi7mcA5+Ktd8A=,iv:8ExFXzBDeyF4s8Zd6jiHTJRZVuEzyL4SSo7bd5n9QjQ=,tag:rMKNYMOB7mPlD5e+N+Ip6A==,type:str]
    EMQX_USER_PASSWORD: ENC[AES256_GCM,data:0RVpJDqEec8=,iv:296t0TRFtrHDgII9qYg2G+wpPDmwbQMVkAEkQxxI3m8=,tag:U+N4QcqQersiH5lMh3phLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SXY1WFp0MnRTc29ITWIz
            MFdSdnoydHhxc2YxZ1kyN1VCWHA4NDN4K2c4CjMyNSsvWUx6SWh6MXhmWFc1dnlR
            WWFMTTV3WUtSZ2hZeXJNVzFrSEg5a3cKLS0tIGpBSSt0eFZkOC9nN1ErZU1semZU
            bVNRclV3bTdpMU1QK1htb3N5eituU2cK7gJAmMox5J7T/hjye/ww30JcNIxAvwsW
            Lttp99Z6sO4WuAP/h3I0fUqNW2IrG+hBZyhOJt4O+aWBshEm0rbLfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-16T09:04:58Z"
    mac: ENC[AES256_GCM,data:WkzygEHZu8ULwuQ5sufaj/Ysj+mU+BIe2BaSL78VkU5oQYYF7h6IOSwC8TZPEY5bC+eD92Zfv0FRkqSJcWgdL8tJhJC8Mps1McPRNkOc5wwp3CiRkCqMQ0QjWEEIK6PFojyqG06uloys4fE8kMv5u+azhlHUlyt7h9JMTwtqOyE=,iv:RXC71C+z7+rREPvwOQvmz1T8tdCHgKP513EIKOUjzzY=,tag:aqPo1vgyezbC5YSWjyJbiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
