---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.1.0
  - name: community.docker
    version: 3.4.8
  - name: community.sops
    version: 1.6.5
roles:
  - name: semuadmin.octoprint
    src: https://github.com/semuconsulting/ansible_octoprint.git
    version: v1.0.7
