apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wDXYlWuDEve053WUKweyl0PL3HdkfowQSFpZZC97aJryITQH,iv:8vXe93eRQdWHqQBtfGVdI5FC1STLIEDprsN4FJUqpGk=,tag:1U3cD4ktPNYC1swoTZcrEg==,type:str]
    credentials.json: ENC[AES256_GCM,data:iZpz66aXbMzPvvZrXSlo0LC9atu5jZy4IegyI3Bgg+6NCrMJuM4/uG4F56Z+S8Z/TXVxvzgcVApQiZnfQp5gpswIpb8d+IGgJFGeFyzvCL5SsYGj8HUhu3ZjK41SVHTCdWsexlj2hUsuu/C+IUzldUULsPY5iZJAOeOnDWYlDulSQttfDvoYtrntKSQa/i2gMMG/p/2b5aaAoAK8Jg4EOFKHHa3u/fBkwoNQ6crF/g==,iv:PrAiIsmQCpBKgNqWA0maU/y3rSOmjMrz7rep1CHFndM=,tag:EqZvyRtfjtHRl5nl4yseKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdVhub0xuSFBPQ0E1azc1
            TnFyVWZOakZsMzh5UW8rZ0NkdThINUg0N1F3CkdydmEranpmdjdQQ0I5blFpQm1y
            NDRpRDllTFgrT2FnVFFmZnVxQTVwbEUKLS0tIFhKVnZkNUt2TlZjOUNWQlJLeE5o
            L3FSZlJuSUZYNHRlNVUxYktmL29XUDgKOAKtD9dxJ9otJ6cUPWbtNegL6stzHUeI
            CR0EBxjm7fnMg/v0B1TQQwKEOrEqEGUzMImfuCY/oDUNA7lqY8FnQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T07:33:15Z"
    mac: ENC[AES256_GCM,data:7vvrGyLwQbdZC81nWQ+qyusb9ywIynp/dswCnZDUvMaquQUaIeKJM84snvqcYl6iDkLDxAwyMENfkiNwDhh0RtHiiCS2BHBOwhk8alkhmJpvmzX5JZn8plwMYFBiRHCVm9Lhv1wvaQ28V3gAES4EvTlpG1NrQ5ni7UYd/skRaMM=,iv:wnU74Hu79OCCwSry/JPVVyElxeGzG+qLv/XAsimGkCk=,tag:qs+Rv5y6Nr6OffaXuGD3sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
