---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mealie:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.12.0
            env:
              BASE_URL: https://mealie.${SECRET_DOMAIN}
              ALLOW_SIGNUP: false
              API_DOCS: false
              SMTP_HOST: ${SMTP_HOST_IP}
              SMTP_PORT: 25
              SMTP_AUTH_STRATEGY: NONE
              SMTP_FROM_EMAIL: mealie@${SECRET_DOMAIN}
              THEME_DARK_PRIMARY:
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                cpu: 200m
                memory: 800Mi
    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      # internal:
      #   enabled: true
      #   className: internal
      #   hosts:
      #     - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN_T}"
      #       paths:
      #         - path: /
      #           service:
      #             identifier: app
      #             port: http
      #   tls:
      #     - hosts:
      #         - *host
    persistence:
      config:
        enabled: true
        existingClaim: mealie-config
        globalMounts:
          - path: /app/data
      # backups:
      #   enabled: true
      #   type: nfs
      #   server: nfs1.home.lan
      #   path: /volume1/k3sCluster/Apps/External/Backups
      #   globalMounts:
      #     - path: /app/data/backups
