---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-restic
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${VOLSYNC_RESTIC_REPOSITORY}/mealie
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_MINIO_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_MINIO_SECRET_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie
  namespace: default
spec:
  sourcePVC: mealie-config
  trigger:
    schedule: 0 7 * * *
  restic:
    copyMethod: Clone
    pruneIntervalDays: 7
    repository: mealie-restic
    cacheCapacity: 8Gi
    cacheStorageClassName: openebs-hostpath
    storageClassName: local-hostpath
    # moverSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    retain:
      daily: 7
      within: 3d
