# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
    namespace: default
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:umH6/b43unBrGRka6FAr7vqLFPWs5hI=,iv:OI0kLBOthlzYfT3ljV6ZNJGwI5v09hA/ul0FHbfPMW8=,tag:06/QbIf3dNhwAmiQ2Jel0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNXRMalpoNGM3cnRQZyt6
            dm1wV1g5MGk2cVJzdlN2VisxL00vdE01WW5jCmM2WlB2c0ZrZmh4ZEFTTUZOczdX
            NTROdkVzZ29rVmw5cXFlY0VDS1FJZjAKLS0tIEJiRWtjK3c1VktodlNDOFJBc2RL
            anAvWEZ0dDJQUklraEhEeWVWRlUyOWMKORsYlu/VCMykic63l5Ov1BTIR2/NWaMy
            4nE5meVSKBHQd/MMftjDTFFD9e3OeP7nZ4sRBFGL+LTV/oJAh1ERYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T12:27:47Z"
    mac: ENC[AES256_GCM,data:Ydh2DF/sqK1iIgfJAHopl471raLIZ67AaSHU+0eYQWmIf0+ERlD4S9J1+utwikTKs7m+k7pfBQQGAsSxFEIcWC2VRohvdVF8/+LoMv1MHmSM3ci81+0NCgcSfX1QwD444frU1/rEcE7BBLKpWqmDyHz2k3F7VSlTPHl2qLHdNtI=,iv:wlCOyjy4iiLx+QDV+hWIOEZK2Ifq51QtweKrjUmz5Bs=,tag:QBehh/t75KjGltOANI1n2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kopia-repository
    namespace: default
stringData:
    token: ENC[AES256_GCM,data:Ll1Nnkqi5TSxgjqWz8e7NXCmAvifARMaOs6XHI2VFB15JxSPh4CC8QruonNKay1nKFreJE2hH+vM3rXJ7aOgdb4XmAVzrFapiqmDsTp0JgZt0KEdn5uSwbhlWCOLHyZtHC/9k/fWX0kT7udckFOI7B2BzjZAgmy1d84tFvTUTZhFo1POAeGmPQyAGuVUIXr0TYFa5+7K1hmiSlMoytYFZolqgefZA+uiFoQzJQ90Ligwr1xbH1NX0rPIPkrRcStHgRvyzwlRCXMM4vCLlAhit1TVSK4jtCEBUMm5ZfnzPdPDjJ53bLuvS6X9dEJls82RSnh1kwRm6QmWvITertV6pb53jeqzdw1HON4ZCh8U2fgfqp/rhAGeGmmc5D1R8kGwBAgEVDxl6BVY5A9bbppgHRd/Dt/IN3AWvD6M0xzNkeUuRdxMVVtzE2bBh3jgu6WC67z470WJmFTVWRk1EHAD6cBBdLXkyAYPxF/ojZ8P3zOjYikeqVoNqW8GKW6qgYPe,iv:J2op78ynfnXkOPOZBakxypkkOTEOVwy6wautFWtLgXY=,tag:npzPOGF/9pZhM1rbHBdEFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNXRMalpoNGM3cnRQZyt6
            dm1wV1g5MGk2cVJzdlN2VisxL00vdE01WW5jCmM2WlB2c0ZrZmh4ZEFTTUZOczdX
            NTROdkVzZ29rVmw5cXFlY0VDS1FJZjAKLS0tIEJiRWtjK3c1VktodlNDOFJBc2RL
            anAvWEZ0dDJQUklraEhEeWVWRlUyOWMKORsYlu/VCMykic63l5Ov1BTIR2/NWaMy
            4nE5meVSKBHQd/MMftjDTFFD9e3OeP7nZ4sRBFGL+LTV/oJAh1ERYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T12:27:47Z"
    mac: ENC[AES256_GCM,data:Ydh2DF/sqK1iIgfJAHopl471raLIZ67AaSHU+0eYQWmIf0+ERlD4S9J1+utwikTKs7m+k7pfBQQGAsSxFEIcWC2VRohvdVF8/+LoMv1MHmSM3ci81+0NCgcSfX1QwD444frU1/rEcE7BBLKpWqmDyHz2k3F7VSlTPHl2qLHdNtI=,iv:wlCOyjy4iiLx+QDV+hWIOEZK2Ifq51QtweKrjUmz5Bs=,tag:QBehh/t75KjGltOANI1n2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
