# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway
    namespace: vpn
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ""
    SERVER_COUNTRIES: ""
    SERVER_REGIONS: ENC[AES256_GCM,data:LJ5KYgV5OXQH,iv:hqXJ4f5u/qN6f8+SYpbtEbgjRpF6Gg4NWi6I9PhFVnM=,tag:esr6V0bZSijJtwptXjJLXQ==,type:str]
    SERVER_HOSTNAMES: ""
    OPENVPN_USER: ENC[AES256_GCM,data:TqfDvCbl7gI=,iv:GQuUMDfsm7EScUWps74BTlnHTR9HAelfLLJaziTvAuc=,tag:XIHWpTbEsTBZPIS0JoOOOg==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:npkzaUng4pehjg==,iv:0cJeV4zjeiyub3F1ynoZ/H+fn4WkcxfK1wxWTYOdNhI=,tag:AK33TiePthOUmzoPml4PHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NEcxOXVQTnpSUnpKQ2R0
            c1lFekRZUmVoWHFWaW5zazRqV0NqWGVRbVgwCk8rc2dTWS9GUUdtYm1nNHdXMzV4
            QmxsaVJrLzFLUkY1WHprem5WaWIrdlkKLS0tIE51dWRGWGMveFhNTS9LRGQ5MUcr
            NWpxQ1Q5UDJBTXg4WmtFRXpnYnFhMzAKBb5Cn18GxtDPASP510vsJF4aa0BQO8vq
            4y3gzxfFGHJt3Bo3+Uq9OROmFqS8OsmFkzwB+6Q6/Qi7tsXFVPeGqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T11:49:05Z"
    mac: ENC[AES256_GCM,data:XjSI44urC881EFj6QG53qM2Xy7wM0ihj8Oq92FL6fA3Vo687jQAtrXAibC6BuVd/NX+A6R5LmRd5jUaASUM7aqme+LGF8yj/WVp6Pcji3ezdaPU8zr12PbOIHLm5ZesrBMsdIv6Mdgj7mDY5/i5+atHFAM/PuJHQgkKWubdk5Co=,iv:wvgPOSoBf8hSnr0q+U/qUohtAWyNlINS3OahjDSv7q0=,tag:YtY4NWjep3jH1YtVj+lTRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
