---
name: "Schedule: Cloudflare Proxied Networks"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_CLOUDFLARE_PROXIED_NETWORKS_FILE: |-
    cluster/apps/default/ingress-nginx/cloudflare-proxied-networks.txt
jobs:
  cloudflare-networks:
    name: Cloudflare Networks
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Cloudflare Proxied Networks
        run: |
          cloudflare_proxied_networks_file=$(find . -name "cloudflare-proxied-networks.txt" -print -quit)
          if [[ ! -f "${cloudflare_proxied_networks_file}" ]]; then
              bash ./.github/scripts/cloudflare-proxied-networks.sh > ${{ env.DEFAULT_CLOUDFLARE_PROXIED_NETWORKS_FILE }}
          else
              bash ./.github/scripts/cloudflare-proxied-networks.sh > "${cloudflare_proxied_networks_file}"
          fi
      - name: Create pull request
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5 # v5.0.0
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          branch: github-action/update-cloudflare-networks
          delete-branch: true
          title: "chore(github-action): update cloudflare networks"
          signoff: true
          commit-message: "chore(github-action): update cloudflare networks"
          body: |
            Update cloudflare networks configmap from https://api.cloudflare.com/client/v4/ips
          labels: |
            renovate/github-action